version = 0.1
[TEST]
[TEST.deploy]
[TEST.deploy.parameters]
stack_name = "starfleet"
s3_bucket = "REPLACE-ME"  # The SAM CLI will generate this with a "guided" deploy option -- or you can just make this yourself.
s3_prefix = "starfleet"
region = "REPLACEME"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]  # Important -- you need these capabilities defined since this creates IAM roles
parameter_overrides = "EnvironmentName=\"TEST\""
image_repository = "REPLACE ME - IF YOU ARE  NOT USING ECR DELETE THIS LINE"

[TEST.validate.parameters]
region = "REPLACEME"
lint = true
template_file = "test_sam_template.yaml"  # Feel free to replace with your own filename

[TEST.build.parameters]
use_container = true
template_file = "test_sam_template.yaml"  # Feel free to replace with your own filename


[PROD]
[PROD.deploy]
[PROD.deploy.parameters]
stack_name = "starfleet"
s3_bucket = "REPLACE-ME"  # The SAM CLI will generate this with a "guided" deploy option -- or you can just make this yourself.
s3_prefix = "starfleet"
region = "REPLACEME"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]  # Important -- you need these capabilities defined since this creates IAM roles
parameter_overrides = "EnvironmentName=\"PROD\""
image_repository = "REPLACE ME - IF YOU ARE  NOT USING ECR DELETE THIS LINE"

[PROD.validate.parameters]
region = "REPLACEME"
lint = true
template_file = "prod_sam_template.yaml"  # Feel free to replace with your own filename

[PROD.build.parameters]
use_container = true
template_file = "prod_sam_template.yaml"  # Feel free to replace with your own filename
